layout_spectrum: 0.9723572
typography_spectrum: 0.5575147
color:
  saturation: 0.5830763
  lightness: 0.5828757
  brandStrength: 0.2154575
  rhythmicContrast: 0.3669739
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Matthowell
